### ISSUE TITLE
Beep Card SVT button

### ISSUE THREAD

**Issue by krisel** [alexneri/afhome-carousel#1]
For inquiry: Down arrow button for SVT only redirects to the second section of the page. Is this an expected behavior? Screenshots below:

![image](https://cloud.githubusercontent.com/assets/20318068/16615198/7ad38e46-43a7-11e6-8ce9-0cbeac924481.png)

![image](https://cloud.githubusercontent.com/assets/20318068/16615206/89b8278c-43a7-11e6-9650-bbcda24ed677.png)

**Comment by alexneri** [comment]
Correct: The down arrow only moves towards the second section.

Thanks! :+1:
