### ISSUE TITLE
Automatic Rotation Cancels

### ISSUE THREAD

**Issue by krisel** [alexneri/afhome-carousel#2]
Slide rotation is working until you manually click on the arrow buttons. After clicking either the left or right arrow, carousel image will no longer rotate. 

Not sure if this is an intended behavior.

**Comment by alexneri** [comment]
I just checked with other implementations of the bxSlider, and yep it seems to be part of the framework's design.

So yep, looks like Working As Designed (WAD)

http://bxslider.com/
